version: '3.9'

services:
  db:
    image: 'postgres:13'
    container_name: 'java-postgres'
    restart: always
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=weather_tracker'
  web:
    build: .
    container_name: java_web_app
    restart: always
    ports:
        - "8080:8080"
    depends_on:
        - db
    environment:
        DB_HOST: db
        DB_PORT: 5432
        DB_NAME: weather_tracker
        DB_USER: postgres
        DB_PASSWORD: postgres